USE MASTER;

-- EXCLUIR E CRIAR O BANCO
DROP DATABASE IF EXISTS AutoTorque;
CREATE DATABASE AutoTorque;

-- UTILIZAR O BANCO QUE FOI CRIADO
USE AutoTorque;

-- CRIAR A TABELA CLIENTE
DROP TABLE IF EXISTS Cliente;
CREATE TABLE Cliente(
    IdCliente INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
	Nome VARCHAR(100) NOT NULL,
    Cpf CHAR(11) UNIQUE NOT NULL,
    Telefone VARCHAR(15) NOT NULL,
    Endereco VARCHAR(255) NOT NULL,
);

-- CRIAR A TABELA VEICULO
DROP TABLE IF EXISTS Veiculo;
CREATE TABLE Veiculo(
    IdVeiculo INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Modelo VARCHAR(100) NOT NULL,
    Marca VARCHAR(100) NOT NULL,
    Ano INT NOT NULL,
    Placa VARCHAR(10) UNIQUE NOT NULL,

	FkIdCliente INT,
    FOREIGN KEY (FkIdCliente) REFERENCES Cliente(IdCliente)
);

-- CRIAR A TABELA FUNCIONARIO
DROP TABLE IF EXISTS Funcionario;
CREATE TABLE Funcionario(
    IdFuncionario INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Nome VARCHAR(100) NOT NULL,
    Cargo VARCHAR(50) NOT NULL,
    Salario DECIMAL(10, 2) NOT NULL,
	Endereco VARCHAR(55) NOT NULL,
);

-- CRIAR A TABELA SERVIÇO
DROP TABLE IF EXISTS Servico;
CREATE TABLE Servico(
    IdServico INT IDENTITY(1,1) PRIMARY KEY NOT NULL,
    Descricao VARCHAR(255) NOT NULL,
	DtInicio DATE NOT NULL,
	DtFim DATE NOT NULL,
	Categoria VARCHAR(50) NOT NULL,

	FkIdFuncionario INT,
	FOREIGN KEY (FkIdFuncionario) REFERENCES Funcionario(IdFuncionario),
);




-- CRIAR A TABELA PAGAMENTO
DROP TABLE IF EXISTS Pagamento;
CREATE TABLE Pagamento(
    IdPagamento INT IDENTITY(1,1) PRIMARY KEY NOT NULL,    
    DtPagamento DATE NOT NULL,
	Parcela INT,
	ValorTotal DECIMAL(18,2) NOT NULL,
	ValorPago DECIMAL(18,2) NOT NULL,
	Troco DECIMAL(18,2),
	ObservacaoInterna VARCHAR(1000),
);